# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [2]:
import numpy as np
import time

In [3]:
import numpy as np
import time

def _time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

def task_3_numpy(n, m, r, c):
    arr = np.ones((n, m), dtype=int)
    arr[r,:] = 0
    arr[:,c] = 0
    return arr

def task_3_loop(n, m, r, c):
    arr = []
    for i in range(n):
        row = []
        for j in range(m):
            if i == r or j == c:
                row.append(0)
            else:
                row.append(1)
        arr.append(row)
    return np.array(arr)

def task_5_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    arr[::2] = 1
    return arr

def task_5_loop(n):
    arr = []
    for i in range(n):
        row = []
        for j in range(n):
            if i % 2 == 0:
                row.append(1)
            else:
                row.append(0)
        arr.append(row)
    return np.array(arr)

def task_7_numpy(arr):
    arr[arr == 0]= -1
    return arr

def task_7_loop(arr):
    for i in range(len(arr)):
        if arr[i] == 0:
            arr[i] = -1
    return arr

def task_9_numpy(n):
    return np.arange(n, -1, -1)

def task_9_loop(n):
    return np.array([i for i in range(n, -1, -1)])

def task_10_numpy(n, m):
    arr = np.random.random((n, m))
    return {
        "array": arr,
        "min": round(arr.min(), 3),
        "max": round(arr.max(), 3),
        "mean": round(arr.mean(), 3),
        "std": round(arr.std(), 3)
    }

def task_12_numpy(n):
    arr = np.ones((n, n))
    arr[0, :] = arr[-1, :] = arr[:, 0] = arr[:, -1] = 0
    return arr

def task_14_numpy():
    return np.tile([[0, 1], [1, 0]], (4, 4))

def task_15_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    arr[:, 1::2] = 1
    return arr

def task_21_numpy(n, m):
    arr = np.random.randint(0, m+1, (n, n))
    arr[arr == arr.max()] *=-1
    return arr

print("Numpy 3:", task_3_numpy(6, 7, 2, 3), "Час:", _time(task_3_numpy, 6, 7, 2, 3)[1])
print("Numpy 5:", task_5_numpy(5), "Час:", _time(task_5_numpy, 5)[1])
print("Numpy 7:", task_7_numpy(np.array([3, 4, 0, 6, 5, 0, 3, 0, 4])), "Час:", _time(task_7_numpy, np.array([3, 4, 0, 6, 5, 0, 3, 0, 4]))[1])
print("Numpy 9:", task_9_numpy(10), "Час:", _time(task_9_numpy, 10)[1])
print("Numpy 10:", task_10_numpy(4, 5), "Час:", _time(task_10_numpy, 4, 5)[1])
print("Numpy 12:", task_12_numpy(4), "Час:", _time(task_12_numpy, 4)[1])
print("Numpy 14:", task_14_numpy(), "Час:", _time(task_14_numpy)[1])
print("Numpy 15:", task_15_numpy(5), "Час:", _time(task_15_numpy, 5)[1])
print("Numpy 21:", task_21_numpy(4, 10), "Час:", _time(task_21_numpy, 4, 10)[1])

print("Цикл 3:", task_3_loop(6, 7, 2, 3), "Час:", _time(task_3_loop, 6, 7, 2, 3)[1])
print("Цикл 5:", task_5_loop(5), "Час:", _time(task_5_loop, 5)[1])
print("Цикл 7:", task_7_loop(np.array([3, 4, 0, 6, 5, 0, 3, 0, 4])), "Час:", _time(task_7_loop, np.array([3, 4, 0, 6, 5, 0, 3, 0, 4]))[1])
print("Цикл 9 :", task_9_loop(10), "Час:", _time(task_9_loop, 10)[1])
print("Цикл 10:", task_10_numpy(4, 5), "Час:", _time(task_10_numpy, 4, 5)[1])
print("Цикл 12:", task_12_numpy(4), "Час:", _time(task_12_numpy, 4)[1])
print("Цикл 14:", task_14_numpy(), "Час:", _time(task_14_numpy)[1])
print("Цикл 15:", task_15_numpy(5), "Час:", _time(task_15_numpy, 5)[1])
print("Цикл 21:", task_21_numpy(4, 10), "Час:", _time(task_21_numpy, 4, 10)[1])




Numpy 3: [[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]] Час: 4.291534423828125e-06
Numpy 5: [[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]] Час: 1.9073486328125e-06
Numpy 7: [ 3  4 -1  6  5 -1  3 -1  4] Час: 2.6226043701171875e-06
Numpy 9: [10  9  8  7  6  5  4  3  2  1  0] Час: 1.1205673217773438e-05
Numpy 10: {'array': array([[0.53257673, 0.4740383 , 0.67287219, 0.71733642, 0.13238761],
       [0.03783031, 0.27106499, 0.59800364, 0.35926716, 0.41625833],
       [0.70544522, 0.47941245, 0.6229408 , 0.01060304, 0.78012766],
       [0.62430874, 0.80672008, 0.26981309, 0.47507995, 0.04166245]]), 'min': 0.011, 'max': 0.807, 'mean': 0.451, 'std': 0.247} Час: 4.482269287109375e-05
Numpy 12: [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]] Час: 3.814697265625e-06
Numpy 14: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1

In [4]:
def solve(A, B):
    array1 = {
        "Крамер": [],
        "Інверсія": [],
        "Рішення": np.linalg.solve(A, B)
    }
    det_A = np.linalg.det(A)
    for i in range(A.shape[1]):
        A_i = A.copy()
        A_i[:, i] = B
        array1["Крамер"].append(np.linalg.det(A_i) / det_A)
    array1["Інверсія"] = np.linalg.inv(A) @ B
    return array1

A2 = np.array([
    [1, 3, 5, 7],
    [3, 5, 7, 1],
    [5, 7, 1, 3],
    [7, 1, 3, 5]
])
B2 = np.array([12, 0, 4, 16])

array1 = solve(A2, B2)
print("Відповідь:", array1)


Відповідь: {'Крамер': [1.0000000000000018, -1.0000000000000009, -9.367506770274745e-17, 2.0], 'Інверсія': array([ 1.00000000e+00, -1.00000000e+00, -1.94289029e-16,  2.00000000e+00]), 'Рішення': array([ 1.00000000e+00, -1.00000000e+00, -1.01770444e-16,  2.00000000e+00])}


In [5]:
def _time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

def matrix_numpy(A, B):
    return (A - B) ** 2 + (A + B) ** 2

def matrix_loop(A, B):
    n, m = A.shape
    result = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            result[i][j] = (A[i][j] - B[i][j]) ** 2 + (A[i][j] + B[i][j]) ** 2
    return result
A = np.array([
    [5, 2, 0],
    [10, 4, 1],
    [7, 3, 2]
])
B = np.array([
    [3, 6, -1],
    [-1, -2, 0],
    [2, 1, 3]
])


print("Numpy:", matrix_numpy(A, B), "Час:", _time(matrix_numpy, A, B)[1])
print("Цикл:", matrix_loop(A, B), "Час:", _time(matrix_loop, A, B)[1])


Numpy: [[ 68  80   2]
 [202  40   2]
 [106  20  26]] Час: 2.6226043701171875e-06
Цикл: [[ 68.  80.   2.]
 [202.  40.   2.]
 [106.  20.  26.]] Час: 9.298324584960938e-06
